### ISSUE TITLE
Fix the sizing of the darn QC plate position figure

### ISSUE THREAD

**Issue by LMBradford** [R-ODAF/R-ODAF_Health_Canada#235]
It's different for every project. Sometimes all squished in, sometimes very spread out. Aaaaaaarg.

**Comment by mattjmeier** [comment]
We could probably do something to calculate the number of plates (i.e., the number of unique values in the batch variable), then make a formula to determine the proper width and height of the total figure that would end up with each facet being a fixed size. Maybe there's a better way? Maybe instead of faceting we make each one a separate plot and use patchwork or cowplot or layout to arrange them?

**Comment by LMBradford** [comment]
Somewhat improved by PR #249 . Closing this for now, but I'm sure we'll find more problems later.
