### ISSUE TITLE
Develop tests for DEseq analysis

### ISSUE THREAD

**Issue by cookkate** [R-ODAF/R-ODAF_Health_Canada#9]
The script right now depends a fair amount on checking by eye to make sure that the data is loaded right. We should replace this with actual tests.

**Comment by mattjmeier** [comment]
Agreed! It's pain when things don't load right and you have to check what's happening manually. Throwing smart errors would be great. Even when DESeq2 throws errors I find often the output confusing and somewhat cryptic...

Anyway one thing to note is that not all the tests we currently have are "required" to pass - for example "are all samples in the sampledata included in the meta data?" is often not true. But we could still have a message displayed that says something like "some of the sample data for this report is being filtered out because it is not in the metadata used to generate the report".

**Comment by mattjmeier** [comment]
@cookkate do you think this is sufficiently done now? I think we do check the data at this point.

The only possible addition would be constructing the expected model matrix based on what we are giving DESeq, but, alternatively, we can just let DESeq crash if it gets to that point and it will throw the right error.

**Comment by cookkate** [comment]
Yeah I'll call this done.
